### PR TITLE
Spiff up the chart and the trade data

### PR DESCRIPTION
**Pull request by mikec**

### CODE REVIEW

**Comment by emaG3m** [comment]
Looks great!! wondering if dates on the access make more sense than Day 1, 2, 3....etc. Also I'm guessing most outcomes tokens will be a lot less than 1 ETH so hopefuly we can account for decimals and stuff on here

**Comment by emaG3m** [comment]
actually now that I think of it, all these scenerios have these outcome tokens as REALLY expensive. Why is that? and is the y axis dynamic?

**Comment by mikec** [comment]
Thanks! Maybe I could convert the labels to short dates (i.e. `Jan 1`, `Mar 2`). As for decimals .. I think that is something we'll have to deal with down the line. The lower/upper bound values are smart contract uint so they can't be decimals .. I think if the oracle result will be a price, we might want to assume that the number is 10**18 based. So for example...

* if we're using the ETH price, and 1 TKN = 0.0345 ETH, that would be represented as `0.345 * (10 ** 18)` or `34500000000000000`
* if we're using DAI (which is more likely to be a greater than 1 amount), and 1 TKN = 26 DAI, that would be represented as `26 * (10 ** 18)` or  `26000000000000000000`

Not to overcomplicated this, but the success metric / oracle resolution number doesn't necessarily have to be a price value .. it could be something like a "health score" from 0 to 1000. For now it's probably safe to assume it's based on a price pair though.

I think I can address both of these relatively quickly...

**Comment by mikec** [comment]
lol just realized that when I started writing that I said we should address it "down the line" then changed my mind while I was writing it and said I'd just fix it :D

**Comment by emaG3m** [comment]
JUst bc something isn't a decimal in a smart contract doesn't mean it can't be in the UI!

**Comment by mikec** [comment]
totally .. it's easy to format in the UI if we know what it represents. Gets a little tricky if it's sometimes one thing and sometimes another. but for now it's probably safe to assume that it's a price pair with 18 decimals.

**Comment by emaG3m** [comment]
👍

**Pull request merged**
